### ISSUE TITLE
Static bindings version

### ISSUE THREAD

**Issue by al1-ce** [schveiguy/raylib-d#35]
Is it possible to have static bindings version to be able to not include dll/so with executable?

**Comment by jordan4ibanez** [comment]
I think this would be a nice addition, could stop people from accidentally destroying a game engine with a ton of mods when all they know how to do is run your game.

**Comment by schveiguy** [comment]
Yes, it is very possible to use static bindings. It's just not something that's as easy to do, so I don't recommend it (especially on Windows). I'm happy to include instructions if you come up with them.

Note that the bindings have nothing to do with static/shared, it's just the library you link against (and all the library dependencies). It's pretty bad on Windows, because I found you needed to build the raylib C library yourself to match the MSVC version.
