### ISSUE TITLE
raygui needs updating

### ISSUE THREAD

**Issue by SpiceyWolf** [schveiguy/raylib-d#7]
I dont know if you guys got an actual generator solution working, but I did notice the raylib-gui wasn't updated... Is there plans to set that up too, or would you like me to get the latest binding for that?

**Comment by schveiguy** [comment]
Yes, nobody we know uses raygui via raylib-d, and since there are no tests, it's hard to know that we got it right. If you are up to the task, please submit a PR!

Thanks!

**Comment by SpiceyWolf** [comment]
The existing raygui that is in there I had already tested quite thoroughly... It didnt seem to have any issues I could find from the existing setup, but it was older and lacks some bug fixes and feature updates... which is why i was interested in getting an update. But yeah, I can go ahead and work on that. Gimme a day or 2 and Ill try to submit something -> I got a gitlab ci thing im working on tonight after work (Hopefully will be done with quickly to get on that).

**Comment by schveiguy** [comment]
I'm not surprised the raygui bindings are viable, since it's a header-only library in the C version. But of course, any changes/improvements we would like to include in our binding.

When you generate the bindings, please update the `generating.md` file to include what you do. I want to make sure future people who might be maintaining don't have to go through what we did. Thanks for helping with this!

**Comment by schveiguy** [comment]
OK, so I just realized that raygui is not header-only in raylib-d, but uses prototypes, which means that in order to use the library, one must build a C library to link against (which is not included with the raygui project).

So raygui needs updating (if necessary) to update the types, but the functions themselves would just be prototypes. I would like to see in a PR also instructions on how a user should build the necessary binding library (maybe a `raygui.md` file in the project dir) for all platforms.

Alternatively, one could port the library to D (or have some process automatically transform it). ImportC would be hugely useful here.

**Comment by SpiceyWolf** [comment]
I meen, raygui the C project is JUST a header... so its pretty ez to just 1-1 port

**Comment by schveiguy** [comment]
The largest problem with translating to D is maintenance. I'm happy to have a D port, but please let me know if you attempt it what is involved. We need to keep it up to date with the latest raygui.

**Comment by SpiceyWolf** [comment]
Just an update to this, I have been poking it for a good minute... however there is an issue I see with future proofing even with a guide... at least at this time...

Right now they seem to be constantly changing how the whole structure of things are, which is problematic concidering dstep is ignoring everything under precomp tags (Like RICONS or standlone etc) which meens alot of stuff is still needing manual changes, and with them doing changes, anything put in a guide to update that is specific may be quickly obsolete in the near future...

I would like, if it is alright with you to just get a version out thats up-to-date right now, then when things seem to calm down with them making major changes try to do another setup that hopefully requires little or no unknowns to the future updating (guide).

**Comment by schveiguy** [comment]
Conversing with someone on discord, and I came to the realization -- since raygui is strictly header, we should copy it instead of asking the user to depend on the C header.

That is, we should copy the C header, give instructions on how to build the C file in this project, and then generate bindings from that. Then we are sure that the binding is properly built.

**Comment by schveiguy** [comment]
I think we just aren't going to support raygui. In the next release, I will remove the module.

Sorry, I think it's just too difficult to get working.

I highly recommend using Glui here: https://code.dlang.org/packages/glui
